{
    "kind": "BuildConfig",
    "apiVersion": "v1",
    "metadata": {
        "name": "golang-ex",
        "creationTimestamp": null,
        "labels": {
            "name": "golang-ex"
        }
    },
    "spec": {
        "triggers": [],
        "source": {
            "type": "Git",
            "git": {
		"uri": "https://github.com/p-sforza/golang-ex.git"
            }
        },
        "strategy": {
            "type": "Custom",
            "customStrategy": {
		"from": {
		    "kind": "DockerImage",
		    "name": "172.30.1.1:5000/test/custombuilder"
		},
		"env": [
		    {
			"name": "TAG",
                        "value": "172.30.1.1:5000/test/golang-ex"
		    }
		],
		"exposeDockerSocket": true,
		"forcePull":true
            }
        }
    }
}
