{
    "kind": "BuildConfig",
    "apiVersion": "v1",
    "metadata": {
        "name": "go-sample-build",
        "creationTimestamp": null,
        "labels": {
            "name": "go-sample-build"
        }
    },
    "spec": {
        "triggers": [],
        "source": {
            "type": "Git",
            "git": {
		"uri": "https://github.com/p-sforza/golang-ex.git"
            }
        },
        "strategy": {
            "type": "Custom",
            "customStrategy": {
		"from": {
		    "kind": "DockerImage",
		    "name": "go-builder"
		},
		"env": [
		    {
			"name": "OPENSHIFT_CUSTOM_BUILD_BASE_IMAGE",
                        #"value": "docker.io/openshift/origin-custom-docker-builder"
                        "value": "go-custom-docker-builder"
		    }
		],
		"exposeDockerSocket": true,
		"forcePull":true
            }
        }
    }
}
